# Generated by Django 3.1.7 on 2021-05-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_attendance_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='statut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
