# Generated by Django 3.1.7 on 2021-05-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20210517_0033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='Attendances',
        ),
    ]
