# Generated by Django 3.1.7 on 2021-05-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20210517_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendances',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='attendances',
            old_name='student_id',
            new_name='student',
        ),
    ]
