# Generated by Django 3.1.7 on 2021-05-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20210517_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='fill',
            fields=[
                ('id_fill', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
