# Generated by Django 3.1.7 on 2021-05-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20210518_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
    ]
