# Generated by Django 3.1.7 on 2021-05-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20210518_2124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Cour',
        ),
    ]
