# Generated by Django 3.1.7 on 2021-05-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20210518_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cour',
            new_name='Course',
        ),
    ]
