# Generated by Django 3.1.7 on 2021-05-23 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20210518_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='displaydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=100)),
                ('Cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='fill_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.fill'),
            preserve_default=False,
        ),
    ]
