# Generated by Django 3.1.7 on 2021-05-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20210524_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='fill_id',
            new_name='fill',
        ),
    ]
