# Generated by Django 3.1.7 on 2021-05-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20210524_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='date',
            field=models.DateField(default='2021-09-03'),
        ),
    ]
