# Generated by Django 3.1.7 on 2021-05-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_fill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(default='2021-02-12'),
        ),
    ]
