# Generated by Django 3.2.3 on 2021-06-02 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_course_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='faceInfo',
            fields=[
                ('faceid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
