# Generated by Django 3.2.3 on 2021-06-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_faceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='fill',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='classroom.fill'),
        ),
        migrations.AddField(
            model_name='user',
            name='fill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.fill'),
        ),
    ]
