# Generated by Django 3.2.3 on 2021-06-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_auto_20210605_2159'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='attendances',
            name='date',
            field=models.DateField(default='2021-02-03'),
        ),
        migrations.AddField(
            model_name='attendances',
            name='hour',
            field=models.TimeField(default='12:41:30'),
        ),
    ]
