# Generated by Django 3.2.3 on 2021-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_auto_20210605_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone_number',
            field=models.IntegerField(default=659994937),
        ),
    ]
