# Generated by Django 3.2.3 on 2021-06-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_auto_20210613_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
