# Generated by Django 3.2.3 on 2021-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0022_auto_20210615_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
